// Color palette library - preset with names and categories
export const colorLibrary = [
  { hex: '#FF6347', name: 'Tomato', categories: ['summer', 'happy'] },
  { hex: '#FFD700', name: 'Gold', categories: ['luxury', 'neutral'] },
  { hex: '#FF4500', name: 'Orange Red', categories: ['summer', 'happy'] },
  { hex: '#32CD32', name: 'Lime Green', categories: ['spring', 'tropical'] },
  { hex: '#4682B4', name: 'Steel Blue', categories: ['technology', 'neutral'] },
  { hex: '#8A2BE2', name: 'Blue Violet', categories: ['vintage', 'luxury'] },
  { hex: '#FF69B4', name: 'Hot Pink', categories: ['happy', 'spring'] },
  { hex: '#FFDAB9', name: 'Peach Puff', categories: ['vintage', 'summer'] },
  { hex: '#00CED1', name: 'Dark Turquoise', categories: ['tropical', 'technology'] },
  { hex: '#DC143C', name: 'Crimson', categories: ['luxury', 'vintage'] },
  { hex: '#228B22', name: 'Forest Green', categories: ['spring', 'neutral'] },
  { hex: '#FF8C00', name: 'Dark Orange', categories: ['summer', 'happy'] },
  { hex: '#8B008B', name: 'Dark Magenta', categories: ['luxury', 'vintage'] },
  { hex: '#5F9EA0', name: 'Cadet Blue', categories: ['technology', 'neutral'] },
  { hex: '#D2691E', name: 'Chocolate', categories: ['vintage', 'neutral'] },
  { hex: '#FF4500', name: 'Orange', categories: ['happy', 'summer'] },
  { hex: '#FF1493', name: 'Deep Pink', categories: ['spring', 'happy'] },
  { hex: '#00BFFF', name: 'Deep Sky Blue', categories: ['technology', 'spring'] },
  { hex: '#ADFF2F', name: 'Green Yellow', categories: ['tropical', 'spring'] },
  { hex: '#FF69B4', name: 'Hot Pink', categories: ['happy', 'spring'] },
  { hex: '#CD5C5C', name: 'Indian Red', categories: ['vintage', 'luxury'] },
  { hex: '#FFD700', name: 'Gold', categories: ['luxury', 'neutral'] },
  { hex: '#F0E68C', name: 'Khaki', categories: ['neutral', 'vintage'] },
  { hex: '#E6E6FA', name: 'Lavender', categories: ['spring', 'vintage'] },
  { hex: '#FF6347', name: 'Tomato', categories: ['summer', 'happy'] },
  { hex: '#40E0D0', name: 'Turquoise', categories: ['tropical', 'technology'] },
  { hex: '#EE82EE', name: 'Violet', categories: ['luxury', 'vintage'] },
  { hex: '#F5DEB3', name: 'Wheat', categories: ['neutral', 'vintage'] },
  { hex: '#F5F5DC', name: 'Beige', categories: ['neutral', 'vintage'] },
  { hex: '#FFE4C4', name: 'Bisque', categories: ['vintage', 'neutral'] },
  { hex: '#0000FF', name: 'Blue', categories: ['primary', 'technology'] },
  { hex: '#A52A2A', name: 'Brown', categories: ['neutral', 'vintage'] },
  { hex: '#DEB887', name: 'Burly Wood', categories: ['neutral', 'vintage'] },
  { hex: '#5F9EA0', name: 'Cadet Blue', categories: ['technology', 'neutral'] },
  { hex: '#7FFF00', name: 'Chartreuse', categories: ['spring', 'tropical'] },
  { hex: '#D2691E', name: 'Chocolate', categories: ['vintage', 'neutral'] },
  { hex: '#FF7F50', name: 'Coral', categories: ['summer', 'happy'] },
  { hex: '#6495ED', name: 'Cornflower Blue', categories: ['technology', 'spring'] },
  { hex: '#FFF8DC', name: 'Cornsilk', categories: ['neutral', 'vintage'] },
  { hex: '#DC143C', name: 'Crimson', categories: ['luxury', 'vintage'] },
  { hex: '#00FFFF', name: 'Cyan', categories: ['technology', 'tropical'] },
  { hex: '#00008B', name: 'Dark Blue', categories: ['technology', 'primary'] },
  { hex: '#008B8B', name: 'Dark Cyan', categories: ['technology', 'tropical'] },
  { hex: '#B8860B', name: 'Dark Goldenrod', categories: ['vintage', 'neutral'] },
  { hex: '#A9A9A9', name: 'Dark Gray', categories: ['neutral', 'technology'] },
  { hex: '#006400', name: 'Dark Green', categories: ['spring', 'neutral'] },
  { hex: '#BDB76B', name: 'Dark Khaki', categories: ['neutral', 'vintage'] },
  { hex: '#8B008B', name: 'Dark Magenta', categories: ['luxury', 'vintage'] },
  { hex: '#556B2F', name: 'Dark Olive Green', categories: ['neutral', 'spring'] },
  { hex: '#FF8C00', name: 'Dark Orange', categories: ['summer', 'happy'] },
  { hex: '#9932CC', name: 'Dark Orchid', categories: ['luxury', 'vintage'] },
  { hex: '#8B0000', name: 'Dark Red', categories: ['vintage', 'luxury'] },
  { hex: '#E9967A', name: 'Dark Salmon', categories: ['summer', 'happy'] },
  { hex: '#8FBC8F', name: 'Dark Sea Green', categories: ['spring', 'neutral'] },
  { hex: '#483D8B', name: 'Dark Slate Blue', categories: ['technology', 'luxury'] },
  { hex: '#2F4F4F', name: 'Dark Slate Gray', categories: ['neutral', 'technology'] },
  { hex: '#00CED1', name: 'Dark Turquoise', categories: ['tropical', 'technology'] },
  { hex: '#9400D3', name: 'Dark Violet', categories: ['luxury', 'vintage'] },
  { hex: '#FF1493', name: 'Deep Pink', categories: ['spring', 'happy'] },
  { hex: '#00BFFF', name: 'Deep Sky Blue', categories: ['technology', 'spring'] },
  { hex: '#696969', name: 'Dim Gray', categories: ['neutral', 'technology'] },
  { hex: '#1E90FF', name: 'Dodger Blue', categories: ['technology', 'primary'] },
  { hex: '#B22222', name: 'Fire Brick', categories: ['vintage', 'luxury'] },
  { hex: '#FFFAF0', name: 'Floral White', categories: ['neutral', 'vintage'] },
  { hex: '#228B22', name: 'Forest Green', categories: ['spring', 'neutral'] },
  { hex: '#FF00FF', name: 'Fuchsia', categories: ['happy', 'luxury'] },
  { hex: '#DCDCDC', name: 'Gainsboro', categories: ['neutral', 'technology'] },
  { hex: '#F8F8FF', name: 'Ghost White', categories: ['neutral', 'vintage'] },
  { hex: '#FFD700', name: 'Gold', categories: ['luxury', 'neutral'] },
  { hex: '#DAA520', name: 'Goldenrod', categories: ['vintage', 'neutral'] },
  { hex: '#808080', name: 'Gray', categories: ['neutral', 'technology'] },
  { hex: '#008000', name: 'Green', categories: ['primary', 'spring'] },
  { hex: '#ADFF2F', name: 'Green Yellow', categories: ['tropical', 'spring'] },
  { hex: '#F0FFF0', name: 'Honeydew', categories: ['neutral', 'vintage'] },
  { hex: '#FF69B4', name: 'Hot Pink', categories: ['happy', 'spring'] },
  { hex: '#CD5C5C', name: 'Indian Red', categories: ['vintage', 'luxury'] },
  { hex: '#4B0082', name: 'Indigo', categories: ['luxury', 'vintage'] },
  { hex: '#FFFFF0', name: 'Ivory', categories: ['neutral', 'vintage'] },
  { hex: '#F0E68C', name: 'Khaki', categories: ['neutral', 'vintage'] },
  { hex: '#E6E6FA', name: 'Lavender', categories: ['spring', 'vintage'] },
  { hex: '#FFF0F5', name: 'Lavender Blush', categories: ['vintage', 'neutral'] },
  { hex: '#7CFC00', name: 'Lawn Green', categories: ['spring', 'tropical'] },
  { hex: '#FFFACD', name: 'Lemon Chiffon', categories: ['happy', 'vintage'] },
  { hex: '#ADD8E6', name: 'Light Blue', categories: ['technology', 'spring'] },
  { hex: '#F08080', name: 'Light Coral', categories: ['summer', 'happy'] },
  { hex: '#E0FFFF', name: 'Light Cyan', categories: ['technology', 'tropical'] },
  { hex: '#FAFAD2', name: 'Light Goldenrod Yellow', categories: ['neutral', 'vintage'] },
  { hex: '#D3D3D3', name: 'Light Gray', categories: ['neutral', 'technology'] },
  { hex: '#90EE90', name: 'Light Green', categories: ['spring', 'neutral'] },
  { hex: '#FFB6C1', name: 'Light Pink', categories: ['happy', 'vintage'] },
  { hex: '#FFA07A', name: 'Light Salmon', categories: ['summer', 'happy'] },
  { hex: '#20B2AA', name: 'Light Sea Green', categories: ['spring', 'neutral'] },
  { hex: '#87CEFA', name: 'Light Sky Blue', categories: ['technology', 'spring'] },
  { hex: '#778899', name: 'Light Slate Gray', categories: ['neutral', 'technology'] },
  { hex: '#B0C4DE', name: 'Light Steel Blue', categories: ['technology', 'neutral'] },
  { hex: '#FFFFE0', name: 'Light Yellow', categories: ['neutral', 'vintage'] },
  { hex: '#00FF00', name: 'Lime', categories: ['spring', 'tropical'] },
  { hex: '#32CD32', name: 'Lime Green', categories: ['spring', 'tropical'] },
  { hex: '#FAF0E6', name: 'Linen', categories: ['neutral', 'vintage'] },
  { hex: '#FF00FF', name: 'Magenta', categories: ['happy', 'luxury'] },
  { hex: '#800000', name: 'Maroon', categories: ['vintage', 'luxury'] },
  { hex: '#66CDAA', name: 'Medium Aquamarine', categories: ['tropical', 'spring'] },
  { hex: '#0000CD', name: 'Medium Blue', categories: ['technology', 'primary'] },
  { hex: '#BA55D3', name: 'Medium Orchid', categories: ['luxury', 'vintage'] },
  { hex: '#9370DB', name: 'Medium Purple', categories: ['luxury', 'vintage'] },
  { hex: '#3CB371', name: 'Medium Sea Green', categories: ['spring', 'neutral'] },
  { hex: '#7B68EE', name: 'Medium Slate Blue', categories: ['technology', 'luxury'] },
  { hex: '#00FA9A', name: 'Medium Spring Green', categories: ['spring', 'tropical'] },
  { hex: '#48D1CC', name: 'Medium Turquoise', categories: ['tropical', 'technology'] },
  { hex: '#C71585', name: 'Medium Violet Red', categories: ['luxury', 'vintage'] },
  { hex: '#191970', name: 'Midnight Blue', categories: ['technology', 'luxury'] },
  { hex: '#F5FFFA', name: 'Mint Cream', categories: ['neutral', 'vintage'] },
  { hex: '#FFE4E1', name: 'Misty Rose', categories: ['vintage', 'neutral'] },
  { hex: '#FFE4B5', name: 'Moccasin', categories: ['neutral', 'vintage'] },
  { hex: '#FFDEAD', name: 'Navajo White', categories: ['neutral', 'vintage'] },
  { hex: '#000080', name: 'Navy', categories: ['technology', 'primary'] },
  { hex: '#FDF5E6', name: 'Old Lace', categories: ['neutral', 'vintage'] },
  { hex: '#808000', name: 'Olive', categories: ['neutral', 'spring'] },
  { hex: '#6B8E23', name: 'Olive Drab', categories: ['neutral', 'spring'] },
  { hex: '#FFA500', name: 'Orange', categories: ['summer', 'happy'] },
  { hex: '#FF4500', name: 'Orange Red', categories: ['summer', 'happy'] },
  { hex: '#DA70D6', name: 'Orchid', categories: ['luxury', 'vintage'] },
  { hex: '#EEE8AA', name: 'Pale Goldenrod', categories: ['neutral', 'vintage'] },
  { hex: '#98FB98', name: 'Pale Green', categories: ['spring', 'neutral'] },
  { hex: '#AFEEEE', name: 'Pale Turquoise', categories: ['tropical', 'technology'] },
  { hex: '#DB7093', name: 'Pale Violet Red', categories: ['luxury', 'vintage'] },
  { hex: '#FFEFD5', name: 'Papaya Whip', categories: ['vintage', 'neutral'] },
  { hex: '#FFDAB9', name: 'Peach Puff', categories: ['vintage', 'summer'] },
  { hex: '#CD853F', name: 'Peru', categories: ['vintage', 'neutral'] },
  { hex: '#FFC0CB', name: 'Pink', categories: ['happy', 'spring'] },
  { hex: '#DDA0DD', name: 'Plum', categories: ['luxury', 'vintage'] },
  { hex: '#B0E0E6', name: 'Powder Blue', categories: ['technology', 'neutral'] },
  { hex: '#800080', name: 'Purple', categories: ['luxury', 'primary'] },
  { hex: '#663399', name: 'Rebecca Purple', categories: ['luxury', 'vintage'] },
  { hex: '#FF0000', name: 'Red', categories: ['primary', 'happy'] },
  { hex: '#BC8F8F', name: 'Rosy Brown', categories: ['neutral', 'vintage'] },
  { hex: '#4169E1', name: 'Royal Blue', categories: ['technology', 'luxury'] },
  { hex: '#8B4513', name: 'Saddle Brown', categories: ['vintage', 'neutral'] },
  { hex: '#FA8072', name: 'Salmon', categories: ['summer', 'happy'] },
  { hex: '#F4A460', name: 'Sandy Brown', categories: ['neutral', 'vintage'] },
  { hex: '#2E8B57', name: 'Sea Green', categories: ['spring', 'neutral'] },
  { hex: '#FFF5EE', name: 'Seashell', categories: ['neutral', 'vintage'] },
  { hex: '#A0522D', name: 'Sienna', categories: ['vintage', 'neutral'] },
  { hex: '#C0C0C0', name: 'Silver', categories: ['neutral', 'technology'] },
  { hex: '#87CEEB', name: 'Sky Blue', categories: ['technology', 'spring'] },
  { hex: '#6A5ACD', name: 'Slate Blue', categories: ['technology', 'luxury'] },
  { hex: '#708090', name: 'Slate Gray', categories: ['neutral', 'technology'] },
  { hex: '#FFFAFA', name: 'Snow', categories: ['neutral', 'vintage'] },
  { hex: '#00FF7F', name: 'Spring Green', categories: ['spring', 'tropical'] },
  { hex: '#4682B4', name: 'Steel Blue', categories: ['technology', 'neutral'] },
  { hex: '#D2B48C', name: 'Tan', categories: ['neutral', 'vintage'] },
  { hex: '#008080', name: 'Teal', categories: ['tropical', 'technology'] },
  { hex: '#D8BFD8', name: 'Thistle', categories: ['vintage', 'neutral'] },
  { hex: '#FF6347', name: 'Tomato', categories: ['summer', 'happy'] },
  { hex: '#40E0D0', name: 'Turquoise', categories: ['tropical', 'technology'] },
  { hex: '#EE82EE', name: 'Violet', categories: ['luxury', 'vintage'] },
  { hex: '#F5DEB3', name: 'Wheat', categories: ['neutral', 'vintage'] },
  { hex: '#FFFFFF', name: 'White', categories: ['neutral', 'technology'] },
  { hex: '#F5F5F5', name: 'White Smoke', categories: ['neutral', 'vintage'] },
  { hex: '#FFFF00', name: 'Yellow', categories: ['primary', 'happy'] },
  { hex: '#9ACD32', name: 'Yellow Green', categories: ['spring', 'tropical'] }
]